#!/usr/bin/env python

import tkinter
if __name__ == '__main__':
    try:
        top = tkinter.Tk()
        top.geometry("260x175")
        label = tkinter.Label(text = "speed")
        label.place(x=20, y=30, width=60, height=25)
        entry = tkinter.Entry(top)
        entry.place(x=90, y=30, width=150, height=25)
        button_pub = tkinter.Button(text = "pub", width = 25,)
        button_stop = tkinter.Button(text = "stop", width = 25)
        button_quit = tkinter.Button(text = "quit", width = 25, command = top.destroy)
        button_pub.place(x=20, y=90, width=100, height=25)
        button_stop.place(x=140, y=90, width=100, height=25)
        button_quit.place(x=20, y=130, width=220, height=25 )
        top.mainloop()
    #try:
    #    talker()
    except rospy.ROSInterruptException:
        top.quit
        pass
